#ifndef KEYBOARD_H
# define KEYBOARD_H

# include "types.h"

typedef enum {
	KEYBOARD_KEY_A = 0x1E,
	KEYBOARD_KEY_B = 0x30,
	KEYBOARD_KEY_C = 0x2E,
	KEYBOARD_KEY_D = 0x20,
	KEYBOARD_KEY_E = 0x12,
	KEYBOARD_KEY_F = 0x21,
	KEYBOARD_KEY_G = 0x22,
	KEYBOARD_KEY_H = 0x23,
	KEYBOARD_KEY_I = 0x17,
	KEYBOARD_KEY_J = 0x24,
	KEYBOARD_KEY_K = 0x25,
	KEYBOARD_KEY_L = 0x26,
	KEYBOARD_KEY_M = 0x32,
	KEYBOARD_KEY_N = 0x31,
	KEYBOARD_KEY_O = 0x18,
	KEYBOARD_KEY_P = 0x19,
	KEYBOARD_KEY_Q = 0x10,
	KEYBOARD_KEY_R = 0x13,
	KEYBOARD_KEY_S = 0x1F,
	KEYBOARD_KEY_T = 0x14,
	KEYBOARD_KEY_U = 0x16,
	KEYBOARD_KEY_V = 0x2F,
	KEYBOARD_KEY_W = 0x11,
	KEYBOARD_KEY_X = 0x2D,
	KEYBOARD_KEY_Y = 0x15,
	KEYBOARD_KEY_Z = 0x2C,
	KEYBOARD_KEY_0 = 0x0B,
	KEYBOARD_KEY_1 = 0x02,
	KEYBOARD_KEY_2 = 0x03,
	KEYBOARD_KEY_3 = 0x04,
	KEYBOARD_KEY_4 = 0x05,
	KEYBOARD_KEY_5 = 0x06,
	KEYBOARD_KEY_6 = 0x07,
	KEYBOARD_KEY_7 = 0x08,
	KEYBOARD_KEY_8 = 0x09,
	KEYBOARD_KEY_9 = 0x0A,
	KEYBOARD_KEY_SPACE = 0x39,
	KEYBOARD_KEY_ENTER = 0x1C,
	KEYBOARD_KEY_BACKSPACE = 0x0E,
	KEYBOARD_KEY_SHIFT_LEFT = 0x2A,
} keyboard_key_t;

typedef enum {
	KEY_RELEASED = 0x80,
	KEY_PRESSED = 0x00
} keyboard_event_t;

# define KEYBOARD_EVENT(scancode) \
	((scancode & KEY_RELEASED) ? KEY_RELEASED : KEY_PRESSED)

# define KEYBOARD_KEY(scancode) \
	((scancode & ~KEY_RELEASED) & 0x7F)

char keyboard_get_char(keyboard_key_t key);
char get_last_pressed_char();

#endif